import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/Colors";
import { Height, Width } from "../../constants/Layout";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "#fff",
    position: "relative",
    flex: 1,
    alignItems: "center",
  },
  header: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    paddingTop: 50,
    paddingBottom: 15,
    paddingLeft: 20,
    paddingRight: 20,
    minHeight: 80,
    backgroundColor: COLORS.tint,
    justifyContent: "space-between",
  },
  routeTitle: {
    color: COLORS.cloudyWhite,
    fontSize: 16,
    letterSpacing: 1,
  },
  name_roi: {
    flexDirection: "row",
    width: Width,
    alignItems: "center",
    justifyContent: "space-evenly",
    backgroundColor: COLORS.tint,
    paddingBottom: 50,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  productName: {
    color: COLORS.cloudyWhite,
    fontSize: 30,
    paddingVertical: 20,
  },
  productRoi: {
    color: COLORS.cloudyWhite,
    fontSize: 14,
    paddingVertical: 20,
  },
  planBox: {
    width: Width / 4,
    height: Height / 10,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 5,
    elevation: 5,
    shadowRadius: 1,
    shadowOpacity: 0.5,
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  planBoxBoldText: {
    fontSize: 12,
    textTransform: "uppercase",
  },
  planBoxLightText: {
    fontSize: 16,
  },
  breakdown: {
    marginTop: 30,
  },
  breakdownTitle: {
    color: COLORS.lightTextColor,
    marginTop: 10,
    fontSize: 13,
    letterSpacing: 2,
    fontWeight: "600",
    textAlign: "center",
  },
  breakdownBox: {
    width: Width / 5,
    height: Height / 10,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 5,
    elevation: 5,
    shadowRadius: 1,
    shadowOpacity: 0.5,
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  breakdownBoxBoldText: {
    fontSize: 12,
    textTransform: "uppercase",
  },
  breakdownBoxLightText: {
    fontSize: 16,
  },
  tableHeadText: {
    fontSize: 16,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  tableText: {
    textTransform: "capitalize",
    fontWeight: "400",
    fontSize: 12,
    color: COLORS.black,
    width: (Width - 20) / 3,
    textAlign: "right",
  },
  tableTextLong: {
    textAlign: "left",
    width: (Width - 20) / 2,
  },
  tableBodyText: {},
  tableFooter: {
    marginTop: 30,
  },
  tableSubFooter: {
    marginTop: 0,
  },
  productCardImageContainer: {
    borderRadius: 10,
    backgroundColor: "transparent",
    position: "absolute",
    // bottom: 60,
    right: 0,
    top: -8,
  },
  productCardImage: {
    height: 70,
    width: 70,
    borderRadius: 12,
    resizeMode: "contain",
    borderRadius: 100,
  },
  selectPlanText: {
    fontSize: 15,
    paddingVertical: 20,
    textAlign: "center",
  },
  descriptionText: {
    textAlign: "center",
    color: "#a6a5a2",
    marginVertical: 10,
    fontSize: 13,
    letterSpacing: 0.05,
    lineHeight: 28,
    paddingVertical: 10,
  },
  modalTextButton: {
    marginVertical: 3,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  modalText: {
    color: "#111111",
    fontSize: 14,
  },
  btn: {
    height: 30,
    paddingHorizontal: 20,
    marginHorizontal: 5,
  },
  investAmount: {
    textAlign: "center",
    paddingVertical: 30,
  },
  payMethodBtn: {
    height: 40,
    paddingVertical: 10,
    borderRadius: 30,
    marginVertical: 5,
  },
  investNowBtn: {
    marginTop: "auto",
    width: "70%",
    marginBottom: 80,
    borderRadius: 30,
  },
});
