export const ActionTypes = {
  AGE: "AGE",
  GENDER: "GENDER",
  MARITAL_STATUS: "MARITAL_STATUS",
  FIRST_NAME: "FIRST_NAME",
  MIDDLE_NAME: "MIDDLE_NAME",
  LAST_NAME: "LAST_NAME",
  PHONE: "PHONE",
  NAME_AS_WITTEN_ON_BVN: "NAME_AS_WITTEN_ON_BVN",
  ACCOUNT_NUMBER: "ACCOUNT_NUMBER",
  BANK_NAME: "BANK_NAME",
  BANK_BRANCH: "BANK_BRANCH",
};
