export const ActionTypes = {
  SET_ACTIVE_INVESTMENTS: "SET_ACTIVE_INVESTMENTS",
  SET_ELAPSED_INVESTMENTS: "SET_ELAPSED_INVESTMENTS",
  SET_INVESTMENTS: "SET_INVESTMENTS",
  SET_PENDING_INVESTMENT: "SET_PENDING_INVESTMENT",
};
